# Generated by Django 3.2.6 on 2022-08-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='name_CH',
            field=models.CharField(default='N', max_length=30, verbose_name='中文類別名稱'),
        ),
    ]
