# Generated by Django 3.2.6 on 2022-08-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20220819_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_id',
            new_name='user',
        ),
    ]
