# Generated by Django 3.2.6 on 2022-08-19 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_rename_user_id_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='time',
        ),
        migrations.RemoveField(
            model_name='income',
            name='time',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
